var hierarchy =
[
    [ "com.github.aites.framework.smartmodule.BigDataCollector", "classcom_1_1github_1_1aites_1_1framework_1_1smartmodule_1_1_big_data_collector.html", null ],
    [ "com.github.aites.framework.rule.SWRLrule.ClassAtom", "classcom_1_1github_1_1aites_1_1framework_1_1rule_1_1_s_w_r_lrule_1_1_class_atom.html", null ],
    [ "com.github.aites.framework.globalknowledge.DBConnectionMgr", "classcom_1_1github_1_1aites_1_1framework_1_1globalknowledge_1_1_d_b_connection_mgr.html", null ],
    [ "com.github.aites.framework.globalknowledge.DBConnector", "classcom_1_1github_1_1aites_1_1framework_1_1globalknowledge_1_1_d_b_connector.html", [
      [ "com.github.aites.framework.dbcomponent.BringColumn", "classcom_1_1github_1_1aites_1_1framework_1_1dbcomponent_1_1_bring_column.html", null ],
      [ "com.github.aites.framework.globalknowledge.ConnectionStarter", "classcom_1_1github_1_1aites_1_1framework_1_1globalknowledge_1_1_connection_starter.html", null ],
      [ "com.github.aites.framework.globalknowledge.LoadScheduleFromStateSet", "classcom_1_1github_1_1aites_1_1framework_1_1globalknowledge_1_1_load_schedule_from_state_set.html", null ]
    ] ],
    [ "com.github.aites.framework.dbcomponent.DBForeignKey", "classcom_1_1github_1_1aites_1_1framework_1_1dbcomponent_1_1_d_b_foreign_key.html", null ],
    [ "com.github.aites.framework.dbcomponent.DBProperty", "classcom_1_1github_1_1aites_1_1framework_1_1dbcomponent_1_1_d_b_property.html", null ],
    [ "com.github.aites.framework.ruleset.DBSchemaLoader", "classcom_1_1github_1_1aites_1_1framework_1_1ruleset_1_1_d_b_schema_loader.html", null ],
    [ "com.github.aites.framework.dbcomponent.DBTable", "classcom_1_1github_1_1aites_1_1framework_1_1dbcomponent_1_1_d_b_table.html", null ],
    [ "com.github.aites.framework.orchestration.Device", "classcom_1_1github_1_1aites_1_1framework_1_1orchestration_1_1_device.html", null ],
    [ "com.github.aites.framework.executor.Effector", "classcom_1_1github_1_1aites_1_1framework_1_1executor_1_1_effector.html", null ],
    [ "com.github.aites.framework.monitor.EnvData", "classcom_1_1github_1_1aites_1_1framework_1_1monitor_1_1_env_data.html", null ],
    [ "com.github.aites.framework.aitesconnector.Factory", "interfacecom_1_1github_1_1aites_1_1framework_1_1aitesconnector_1_1_factory.html", null ],
    [ "com.github.aites.framework.monitor.HRAlgorithm", "interfacecom_1_1github_1_1aites_1_1framework_1_1monitor_1_1_h_r_algorithm.html", null ],
    [ "com.github.aites.framework.smartmodule.JayhonConnector", "classcom_1_1github_1_1aites_1_1framework_1_1smartmodule_1_1_jayhon_connector.html", null ],
    [ "com.github.aites.framework.framework.LocalAiTESManager", "classcom_1_1github_1_1aites_1_1framework_1_1framework_1_1_local_ai_t_e_s_manager.html", null ],
    [ "com.github.aites.framework.log.LogWritter", "classcom_1_1github_1_1aites_1_1framework_1_1log_1_1_log_writter.html", null ],
    [ "com.github.aites.framework.log.LogWritter.LogWritterSingleton", "classcom_1_1github_1_1aites_1_1framework_1_1log_1_1_log_writter_1_1_log_writter_singleton.html", null ],
    [ "com.github.aites.framework.aitesmanager.Manager", "classcom_1_1github_1_1aites_1_1framework_1_1aitesmanager_1_1_manager.html", null ],
    [ "com.github.aites.framework.aitesconnector.ManagerAF", "classcom_1_1github_1_1aites_1_1framework_1_1aitesconnector_1_1_manager_a_f.html", null ],
    [ "com.github.aites.framework.communicate.DataTransfer.MQTTSingleton", "classcom_1_1github_1_1aites_1_1framework_1_1communicate_1_1_data_transfer_1_1_m_q_t_t_singleton.html", null ],
    [ "com.github.aites.framework.ruleset.OWLClassGenerator", "classcom_1_1github_1_1aites_1_1framework_1_1ruleset_1_1_o_w_l_class_generator.html", null ],
    [ "com.github.aites.framework.ruleset.OWLPropertyGenerator", "classcom_1_1github_1_1aites_1_1framework_1_1ruleset_1_1_o_w_l_property_generator.html", null ],
    [ "com.github.aites.framework.orchestration.Participants", "classcom_1_1github_1_1aites_1_1framework_1_1orchestration_1_1_participants.html", null ],
    [ "com.github.aites.framework.orchestration.Participants.ParticipantsSingleton", "classcom_1_1github_1_1aites_1_1framework_1_1orchestration_1_1_participants_1_1_participants_singleton.html", null ],
    [ "com.github.aites.framework.planner.Plan", "classcom_1_1github_1_1aites_1_1framework_1_1planner_1_1_plan.html", null ],
    [ "com.github.aites.framework.planner.PlanManager", "classcom_1_1github_1_1aites_1_1framework_1_1planner_1_1_plan_manager.html", null ],
    [ "com.github.aites.framework.monitor.PreProcessor", "interfacecom_1_1github_1_1aites_1_1framework_1_1monitor_1_1_pre_processor.html", null ],
    [ "com.github.aites.framework.rule.RuleManager", "classcom_1_1github_1_1aites_1_1framework_1_1rule_1_1_rule_manager.html", null ],
    [ "com.github.aites.framework.ruleset.RuleSetBody", "classcom_1_1github_1_1aites_1_1framework_1_1ruleset_1_1_rule_set_body.html", null ],
    [ "com.github.aites.framework.ruleset.RuleSetGenerator", "classcom_1_1github_1_1aites_1_1framework_1_1ruleset_1_1_rule_set_generator.html", null ],
    [ "com.github.aites.framework.ruleset.RuleSetManager", "classcom_1_1github_1_1aites_1_1framework_1_1ruleset_1_1_rule_set_manager.html", null ],
    [ "com.github.aites.framework.ruleset.RuleSetParser", "classcom_1_1github_1_1aites_1_1framework_1_1ruleset_1_1_rule_set_parser.html", null ],
    [ "com.github.aites.framework.executor.Scheduler", "classcom_1_1github_1_1aites_1_1framework_1_1executor_1_1_scheduler.html", null ],
    [ "com.github.aites.framework.executor.Scheduler.SchedulerSingleton", "classcom_1_1github_1_1aites_1_1framework_1_1executor_1_1_scheduler_1_1_scheduler_singleton.html", null ],
    [ "com.github.aites.framework.smartmodule.SmartModuleChooser", "classcom_1_1github_1_1aites_1_1framework_1_1smartmodule_1_1_smart_module_chooser.html", null ],
    [ "com.github.aites.framework.planner.StateCombinationCalculator", "classcom_1_1github_1_1aites_1_1framework_1_1planner_1_1_state_combination_calculator.html", null ],
    [ "com.github.aites.framework.analyzer.StateCombiner", "classcom_1_1github_1_1aites_1_1framework_1_1analyzer_1_1_state_combiner.html", null ],
    [ "com.github.aites.framework.analyzer.StateReasoner", "interfacecom_1_1github_1_1aites_1_1framework_1_1analyzer_1_1_state_reasoner.html", null ],
    [ "com.github.aites.framework.rule.SWRLrule", "classcom_1_1github_1_1aites_1_1framework_1_1rule_1_1_s_w_r_lrule.html", null ],
    [ "com.github.aites.framework.test.TestMain", "classcom_1_1github_1_1aites_1_1framework_1_1test_1_1_test_main.html", null ],
    [ "com.github.aites.framework.framework.Timer", "classcom_1_1github_1_1aites_1_1framework_1_1framework_1_1_timer.html", null ],
    [ "com.github.aites.framework.framework.Timer.TimerSingleton", "classcom_1_1github_1_1aites_1_1framework_1_1framework_1_1_timer_1_1_timer_singleton.html", null ],
    [ "MqttCallback", null, [
      [ "com.github.aites.framework.communicate.DataTransfer", "classcom_1_1github_1_1aites_1_1framework_1_1communicate_1_1_data_transfer.html", null ],
      [ "com.github.aites.framework.test.TestMqttClient", "classcom_1_1github_1_1aites_1_1framework_1_1test_1_1_test_mqtt_client.html", null ]
    ] ]
];